<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>aspnet-WsServer-2670D944-BCB8-41AB-B27E-24D82E676C94</UserSecretsId>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MemoryPack" Version="1.21.4" />
	</ItemGroup>

	<!-- output memorypack TypeScript code to directory -->
	<!--<ItemGroup>
		<CompilerVisibleProperty Include="MemoryPackGenerator_TypeScriptOutputDirectory" />
	</ItemGroup>
	<PropertyGroup>
		<MemoryPackGenerator_TypeScriptOutputDirectory>$(MSBuildProjectDirectory)\..\..\WsCore.Client\src\network\protocol</MemoryPackGenerator_TypeScriptOutputDirectory>
	</PropertyGroup>-->

</Project>
